query Project($slug: String!) {
	project(where: { slug: $slug }) {
		id
		slug
		title
		description
		content
		experience {
			id
			jobTitle
			company
			logo {
				url
			}
			brandColor {
				hex
			}
			dateRange
		}
	}
}
