import {
  ChakraUiLogoIcon,
  ChartGptLogoIcon,
  ClickUpLogoIcon,
  DashedCircleIcon,
  HaliteLogoIcon,
  HeronLogoIcon,
  HygraphLogoIcon,
  MeeshkanLogoIcon,
  OwnCoLogoIcon,
  RoopairsLogoIcon,
  SaasUILogoIcon,
  TaiaLogoIcon,
  WhopLogoIcon
} from "@/components/icons";
import { ExperienceCardProps } from "@/components/landing-sections/career-experience";

// This is temporary before extracting the data to a CMS
export const rawExperiences: ExperienceCardProps[] = [
  {
    company: "Halite.app",
    title: "Design/Product Engineer",
    founder: true,
    contract: false,
    dateRange: "September 2023 - Present",
    description: [
      "I am the only designer and engineer on the team. I have designed, prototyped, tested and built both the app and marketing website.",
      "The app is built with Chakra UI, Saas UI, TypeScript, Next.js, and GraphQL, and the website with Framer",
      "This is a data and charts heavy product, so I dove deep into the dense display of data, by utilizing React table, Chart.js and Framer Motion where applicable",
    ],
    brandColor: "#44403C",
    logo: <HaliteLogoIcon />,
    skills: [
      "typescript",
      "react",
      "nextjs",
      "graphql",
      "frontend",
      "framer-motion",
      "product-management",
      "web-design",
      "operations",
      "sales",
      "backend",
      "product-design",
    ],
  },
  {
    company: "Roopairs",
    title: "Design Engineer",
    founder: false,
    contract: true,
    dateRange: "November 2023 - Present",
    description: [
      "I was brought on to help with the design and implementation of the new version of the product. I led the development and advancement of their bespoke design system.",
      "I implemented the bespoke design system based on their existing repo and wants using CSS modules, Radix primitives and in React",
      "I implemented the many of the components in both Figma and in the codebase, working with the team's designer for the rest. I also worked with the team to refactor them in the product.",
      "A significant part of the project was in educating the team on design system principles. I created a documentation site for the design system using Storybook to help with this.",
    ],
    brandColor: "#1F3730",
    logo: <RoopairsLogoIcon />,
    skills: [
      "design-systems",
      "react",
      "frontend",
      "typescript",
      "product-design",
      "nextjs",
      "framer-motion",
    ],
  },
  {
    company: "ChartGPT",
    title: "Open source contributor",
    founder: false,
    contract: false,
    dateRange: "Indefinite",
    description: [
      "I joined this project as the only designer, and frontend specific engineer.",
      "I implemented a redesigned interface and deep customization options for the user.",
      "I implemented Tremor.so charts and Chart.js for the chart types unsupported by Tremor.",
    ],
    brandColor: "#2F80ED",
    logo: <ChartGptLogoIcon />,
    skills: [
      "open-source",
      "design-systems",
      "react",
      "frontend",
      "typescript",
      "product-design",
      "nextjs",
      "framer-motion",
    ],
  },
  {
    company: "Whop",
    title: "Design/Product Engineer",
    founder: false,
    contract: false,
    dateRange: "February 2023 - August 2023",
    description: [
      "Created a bespoke design system using Tailwind, Radix ui, and storybook. Created more than 65 components from idea to production package. The design system received incredibly positive reviews and adoption by the entire engineering team. The project expanded from an internal use to open sourcing, which opened a new opportunity for high growth of the product with a developer-app's platform launching on its back.",
      "Led the team to polished design and implementation across the product. Added micro-animations with accessible fallbacks",
      "Led documentation with Storybook and internal tooling and held demos of releases as well as open critiques for clear understanding of the design system.",
      "Mentored the designer and front-end teams on design systems",
      "I built custom Figma dev tooling for handoff in the design system component's API directly",
    ],
    brandColor: "#FF6243",
    logo: <WhopLogoIcon />,
    skills: [
      "design-systems",
      "framer-motion",
      "frontend",
      "nextjs",
      "product-design",
      "react",
      "storybook",
      "typescript",
      "product-management",
      "graphql",
      "open-source",
    ],
  },
  {
    company: "OwnCo",
    title: "Design/Product Engineer",
    founder: false,
    contract: true,
    dateRange: "September 2022 - March 2023",
    description: [
      "Led the redesign of the product, in both UI and code.",
      "The focus of the new version was on clean UI with intentional UX and tapped into strategy goals (Listening to customers) that was previously missing. Implemented a design-system approach to building, to ensure polished and fast shipping. This included things like graphql codegen + the design system and Formik to auto generate forms.",
      "Implemented a modern stack: Next.js + Vercel, Chakra UI, Saas UI, Clerk, PlanetScale + Pothos + Prisma; and mentored the engineers through the transition",
    ],
    brandColor: "#132CFB",
    logo: <OwnCoLogoIcon />,
    skills: [
      "frontend",
      "backend",
      "framer-motion",
      "product-management",
      "product-design",
      "typescript",
      "operations",
      "graphql",
      "react",
      "nextjs",
    ],
  },
  {
    company: "Saas UI",
    title: "Open source contributor",
    founder: false,
    contract: false,
    dateRange: "Indefinite",
    description: [
      "I became very close with Eelco the creator of Saas UI because of my knack for digging deep with what the project could do.",
      "My contributions were mostly around beta testing & bug fixing. I also contribute to the documentation when I figure out how to do something that is missing. For example in the `AppLayout` component, there is a hidden `aside` prop that allow for a right-hand sidebar great for active workspaces.",
      "I've also collaborated on designing clear and consistent Component APIs such as for `CheckboxTree` and `SegmentedControl`",
    ],
    brandColor: "#8952e0",
    logo: <SaasUILogoIcon />,
    skills: [
      "open-source",
      "design-systems",
      "react",
      "frontend",
      "typescript",
      "framer-motion",
    ],
  },
  {
    company: "Heron",
    title: "Design/Product Engineer",
    founder: true,
    contract: false,
    dateRange: "January 2022 - August 2022",
    description: [
      "Designed and Developed an MVP from discovery phase to the delivery phase. Utilized React, Next.js, Typescript, GraphQL.",
      "Focused on clean UI, as the app was heavy on data and tables.",
      "I created a Customer Advisory Board that led to the first customers co-developing the app.",
      "Designed the website (and built), pitch deck, and social media promotional images.",
    ],
    brandColor: "#127B75",
    logo: <HeronLogoIcon />,
    skills: [
      "backend",
      "customer-support",
      "framer-motion",
      "frontend",
      "graphql",
      "marketing",
      "nextjs",
      "operations",
      "product-design",
      "product-management",
      "react",
      "sales",
      "typescript",
      "web-design",
    ],
  },
  {
    company: "Chakra UI",
    title: "Open source contributor",
    founder: false,
    contract: false,
    dateRange: "Indefinite",
    description: [
      "I so much enjoyed using this design system as a consumer, that I decided to contribute to it. I've contributed to the docs, the website, and the codebase on numerous occasions.",
      "My favorite thing to contribute to is the design of Component APIs",
    ],
    brandColor: "#319795",
    logo: <ChakraUiLogoIcon />,
    skills: [
      "framer-motion",
      "frontend",
      "nextjs",
      "product-design",
      "react",
      "typescript",
      "web-design",
      "design-systems",
      "open-source",
    ],
  },
  {
    company: "Meeshkan",
    title: "Design/Product Engineer",
    founder: true,
    contract: false,
    dateRange: "March 2020 - January 2022",
    description: [
      "I was the sole designer, led a team of developers and business people and was a co-founder, speaking with clients and driving vision.",
      "Led a team of engineers on the creation of the MVP from concept, to testing and first clients.",
      "Designed and built the website in Gatsby. Implemented GraphCMS (Now HyGraph) for the marketing team. Using some clever GraphQL unions, made this almost a drag and drop website builder for them to experiment with.",
      "Built the documentation and led the product walkthroughs (live and async) for clients.",
      "Implemented Next.js, Chakra UI, TypeScript, and GraphQL across the product.",
    ],
    brandColor: "#DC1853",
    logo: <MeeshkanLogoIcon />,
    skills: [
      "operations",
      "marketing",
      "sales",
      "customer-support",
      "product-management",
      "backend",
      "framer-motion",
      "frontend",
      "graphql",
      "nextjs",
      "product-design",
      "react",
      "typescript",
      "web-design",
    ],
  },
  {
    company: "Hygraph",
    title: "Web Designer & Developer",
    founder: false,
    contract: true,
    dateRange: "November 2018 - January 2020",
    description: [
      "I operated as the team's sole designer",
      "I worked on the marketing site, documentation, and building example projects with both Next.js and Gatsby. I often found that the question I was answering for users was 'How do I use GraphQL?' and 'What is GraphQL?'",
      "I designed, wrote and developed 25+ landing pages, using Hygraph, JavaScript and covering CMS + GraphQL topics",
      "I participated in the re-design of the web app: collaborated with product and prototyped designs/flows"
    ],
    brandColor: "#6246EA",
    logo: <HygraphLogoIcon />,
    skills: [
      "graphql",
      "marketing",
      "web-design",
      "product-design",
      "react",
      "nextjs",
      "frontend",
    ],
  },
  {
    company: "TAIA",
    title: "Product",
    founder: false,
    contract: false,
    dateRange: "March 2018 - November 2018",
    description: [
      "As the first full-time employee, I took on many roles. My main focuses were to design & execute the product, coach the sales & marketing teams which I helped hire, & represent the product through public speaking at events.",
      "I taught myself how to code here while developing the landing page and product.",
    ],
    brandColor: "#1caac6",
    logo: <TaiaLogoIcon />,
    skills: [
      "operations",
      "sales",
      "marketing",
      "frontend",
      "product-design",
      "product-management",
      "react",
      "web-design",
    ],
  },
  {
    company: "ClickUp",
    title: "Marketing Content Manager",
    founder: false,
    contract: false,
    dateRange: "December 2017 - April 2018",
    description: [
      "My first entry into tech, I worked as a content manager for ClickUp.",
      "I wrote copy for and designed landing pages, wrote blog posts, created videos, and managed the social media accounts. I taught myself how to design here while doing landing pages.",
    ],
    brandColor: "#7b68ee",
    logo: <ClickUpLogoIcon />,
    skills: ["marketing", "web-design", "customer-support", "sales"],
  },
  {
    company: "Bare Peak",
    title: "Founder",
    founder: true,
    contract: false,
    dateRange: "December 2017 - April 2018",
    description: [
      "I dropped out of college to pursue a startup idea with an accelerator. This was a 3D-printed women's travel shoe where the mid-sole stayed the same and the uppers switched out.",
      "I designed the shoe, as well the website, then sourced the production materials and created a physical prototype.",
      "A large part of this experience was learning how to pitch and present to investors. I also started learning how to manage a team.",
      "My co-founder and I went through Slovenia's biggest accelerator program: ABC accelerator. We secured good partnerships and advisors, but ultimately shut down due to lack of funding."
    ],
    brandColor: "#719266",
    logo: <DashedCircleIcon size={18} className='text-white' />,
    skills: ["operations", "sales", "marketing", "customer-support"],
  },
];
